require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnnotationSourcesController do

  # This should return the minimal set of attributes required to create a valid
  # AnnotationSource. As you add validations to AnnotationSource, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all annotation_sources as @annotation_sources" do
      annotation_source = AnnotationSource.create! valid_attributes
      get :index
      assigns(:annotation_sources).should eq([annotation_source])
    end
  end

  describe "GET show" do
    it "assigns the requested annotation_source as @annotation_source" do
      annotation_source = AnnotationSource.create! valid_attributes
      get :show, :id => annotation_source.id.to_s
      assigns(:annotation_source).should eq(annotation_source)
    end
  end

  describe "GET new" do
    it "assigns a new annotation_source as @annotation_source" do
      get :new
      assigns(:annotation_source).should be_a_new(AnnotationSource)
    end
  end

  describe "GET edit" do
    it "assigns the requested annotation_source as @annotation_source" do
      annotation_source = AnnotationSource.create! valid_attributes
      get :edit, :id => annotation_source.id.to_s
      assigns(:annotation_source).should eq(annotation_source)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AnnotationSource" do
        expect {
          post :create, :annotation_source => valid_attributes
        }.to change(AnnotationSource, :count).by(1)
      end

      it "assigns a newly created annotation_source as @annotation_source" do
        post :create, :annotation_source => valid_attributes
        assigns(:annotation_source).should be_a(AnnotationSource)
        assigns(:annotation_source).should be_persisted
      end

      it "redirects to the created annotation_source" do
        post :create, :annotation_source => valid_attributes
        response.should redirect_to(AnnotationSource.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved annotation_source as @annotation_source" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnnotationSource.any_instance.stub(:save).and_return(false)
        post :create, :annotation_source => {}
        assigns(:annotation_source).should be_a_new(AnnotationSource)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnnotationSource.any_instance.stub(:save).and_return(false)
        post :create, :annotation_source => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested annotation_source" do
        annotation_source = AnnotationSource.create! valid_attributes
        # Assuming there are no other annotation_sources in the database, this
        # specifies that the AnnotationSource created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AnnotationSource.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => annotation_source.id, :annotation_source => {'these' => 'params'}
      end

      it "assigns the requested annotation_source as @annotation_source" do
        annotation_source = AnnotationSource.create! valid_attributes
        put :update, :id => annotation_source.id, :annotation_source => valid_attributes
        assigns(:annotation_source).should eq(annotation_source)
      end

      it "redirects to the annotation_source" do
        annotation_source = AnnotationSource.create! valid_attributes
        put :update, :id => annotation_source.id, :annotation_source => valid_attributes
        response.should redirect_to(annotation_source)
      end
    end

    describe "with invalid params" do
      it "assigns the annotation_source as @annotation_source" do
        annotation_source = AnnotationSource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnnotationSource.any_instance.stub(:save).and_return(false)
        put :update, :id => annotation_source.id.to_s, :annotation_source => {}
        assigns(:annotation_source).should eq(annotation_source)
      end

      it "re-renders the 'edit' template" do
        annotation_source = AnnotationSource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnnotationSource.any_instance.stub(:save).and_return(false)
        put :update, :id => annotation_source.id.to_s, :annotation_source => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested annotation_source" do
      annotation_source = AnnotationSource.create! valid_attributes
      expect {
        delete :destroy, :id => annotation_source.id.to_s
      }.to change(AnnotationSource, :count).by(-1)
    end

    it "redirects to the annotation_sources list" do
      annotation_source = AnnotationSource.create! valid_attributes
      delete :destroy, :id => annotation_source.id.to_s
      response.should redirect_to(annotation_sources_url)
    end
  end

end
