require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeAnalysesController do

  # This should return the minimal set of attributes required to create a valid
  # DeAnalysis. As you add validations to DeAnalysis, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all de_analyses as @de_analyses" do
      de_analysis = DeAnalysis.create! valid_attributes
      get :index
      assigns(:de_analyses).should eq([de_analysis])
    end
  end

  describe "GET show" do
    it "assigns the requested de_analysis as @de_analysis" do
      de_analysis = DeAnalysis.create! valid_attributes
      get :show, :id => de_analysis.id.to_s
      assigns(:de_analysis).should eq(de_analysis)
    end
  end

  describe "GET new" do
    it "assigns a new de_analysis as @de_analysis" do
      get :new
      assigns(:de_analysis).should be_a_new(DeAnalysis)
    end
  end

  describe "GET edit" do
    it "assigns the requested de_analysis as @de_analysis" do
      de_analysis = DeAnalysis.create! valid_attributes
      get :edit, :id => de_analysis.id.to_s
      assigns(:de_analysis).should eq(de_analysis)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DeAnalysis" do
        expect {
          post :create, :de_analysis => valid_attributes
        }.to change(DeAnalysis, :count).by(1)
      end

      it "assigns a newly created de_analysis as @de_analysis" do
        post :create, :de_analysis => valid_attributes
        assigns(:de_analysis).should be_a(DeAnalysis)
        assigns(:de_analysis).should be_persisted
      end

      it "redirects to the created de_analysis" do
        post :create, :de_analysis => valid_attributes
        response.should redirect_to(DeAnalysis.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved de_analysis as @de_analysis" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeAnalysis.any_instance.stub(:save).and_return(false)
        post :create, :de_analysis => {}
        assigns(:de_analysis).should be_a_new(DeAnalysis)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeAnalysis.any_instance.stub(:save).and_return(false)
        post :create, :de_analysis => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested de_analysis" do
        de_analysis = DeAnalysis.create! valid_attributes
        # Assuming there are no other de_analyses in the database, this
        # specifies that the DeAnalysis created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DeAnalysis.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => de_analysis.id, :de_analysis => {'these' => 'params'}
      end

      it "assigns the requested de_analysis as @de_analysis" do
        de_analysis = DeAnalysis.create! valid_attributes
        put :update, :id => de_analysis.id, :de_analysis => valid_attributes
        assigns(:de_analysis).should eq(de_analysis)
      end

      it "redirects to the de_analysis" do
        de_analysis = DeAnalysis.create! valid_attributes
        put :update, :id => de_analysis.id, :de_analysis => valid_attributes
        response.should redirect_to(de_analysis)
      end
    end

    describe "with invalid params" do
      it "assigns the de_analysis as @de_analysis" do
        de_analysis = DeAnalysis.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeAnalysis.any_instance.stub(:save).and_return(false)
        put :update, :id => de_analysis.id.to_s, :de_analysis => {}
        assigns(:de_analysis).should eq(de_analysis)
      end

      it "re-renders the 'edit' template" do
        de_analysis = DeAnalysis.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeAnalysis.any_instance.stub(:save).and_return(false)
        put :update, :id => de_analysis.id.to_s, :de_analysis => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested de_analysis" do
      de_analysis = DeAnalysis.create! valid_attributes
      expect {
        delete :destroy, :id => de_analysis.id.to_s
      }.to change(DeAnalysis, :count).by(-1)
    end

    it "redirects to the de_analyses list" do
      de_analysis = DeAnalysis.create! valid_attributes
      delete :destroy, :id => de_analysis.id.to_s
      response.should redirect_to(de_analyses_url)
    end
  end

end
