require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GeneOntologiesController do

  # This should return the minimal set of attributes required to create a valid
  # GeneOntology. As you add validations to GeneOntology, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all gene_ontologies as @gene_ontologies" do
      gene_ontology = GeneOntology.create! valid_attributes
      get :index
      assigns(:gene_ontologies).should eq([gene_ontology])
    end
  end

  describe "GET show" do
    it "assigns the requested gene_ontology as @gene_ontology" do
      gene_ontology = GeneOntology.create! valid_attributes
      get :show, :id => gene_ontology.id.to_s
      assigns(:gene_ontology).should eq(gene_ontology)
    end
  end

  describe "GET new" do
    it "assigns a new gene_ontology as @gene_ontology" do
      get :new
      assigns(:gene_ontology).should be_a_new(GeneOntology)
    end
  end

  describe "GET edit" do
    it "assigns the requested gene_ontology as @gene_ontology" do
      gene_ontology = GeneOntology.create! valid_attributes
      get :edit, :id => gene_ontology.id.to_s
      assigns(:gene_ontology).should eq(gene_ontology)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GeneOntology" do
        expect {
          post :create, :gene_ontology => valid_attributes
        }.to change(GeneOntology, :count).by(1)
      end

      it "assigns a newly created gene_ontology as @gene_ontology" do
        post :create, :gene_ontology => valid_attributes
        assigns(:gene_ontology).should be_a(GeneOntology)
        assigns(:gene_ontology).should be_persisted
      end

      it "redirects to the created gene_ontology" do
        post :create, :gene_ontology => valid_attributes
        response.should redirect_to(GeneOntology.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gene_ontology as @gene_ontology" do
        # Trigger the behavior that occurs when invalid params are submitted
        GeneOntology.any_instance.stub(:save).and_return(false)
        post :create, :gene_ontology => {}
        assigns(:gene_ontology).should be_a_new(GeneOntology)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GeneOntology.any_instance.stub(:save).and_return(false)
        post :create, :gene_ontology => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gene_ontology" do
        gene_ontology = GeneOntology.create! valid_attributes
        # Assuming there are no other gene_ontologies in the database, this
        # specifies that the GeneOntology created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GeneOntology.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => gene_ontology.id, :gene_ontology => {'these' => 'params'}
      end

      it "assigns the requested gene_ontology as @gene_ontology" do
        gene_ontology = GeneOntology.create! valid_attributes
        put :update, :id => gene_ontology.id, :gene_ontology => valid_attributes
        assigns(:gene_ontology).should eq(gene_ontology)
      end

      it "redirects to the gene_ontology" do
        gene_ontology = GeneOntology.create! valid_attributes
        put :update, :id => gene_ontology.id, :gene_ontology => valid_attributes
        response.should redirect_to(gene_ontology)
      end
    end

    describe "with invalid params" do
      it "assigns the gene_ontology as @gene_ontology" do
        gene_ontology = GeneOntology.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GeneOntology.any_instance.stub(:save).and_return(false)
        put :update, :id => gene_ontology.id.to_s, :gene_ontology => {}
        assigns(:gene_ontology).should eq(gene_ontology)
      end

      it "re-renders the 'edit' template" do
        gene_ontology = GeneOntology.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GeneOntology.any_instance.stub(:save).and_return(false)
        put :update, :id => gene_ontology.id.to_s, :gene_ontology => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gene_ontology" do
      gene_ontology = GeneOntology.create! valid_attributes
      expect {
        delete :destroy, :id => gene_ontology.id.to_s
      }.to change(GeneOntology, :count).by(-1)
    end

    it "redirects to the gene_ontologies list" do
      gene_ontology = GeneOntology.create! valid_attributes
      delete :destroy, :id => gene_ontology.id.to_s
      response.should redirect_to(gene_ontologies_url)
    end
  end

end
